<?php
class SisEmployeeCandidateAfwStructure
{
    public static function initInstance(&$obj)
    {
        if ($obj instanceof EmployeeCandidate) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD = '';
            $obj->ORDER_BY_FIELDS = 'orgunit_id,campaign_id,candidate_hdate';
            $obj->UNIQUE_KEY = array("orgunit_id","campaign_id","customer_id");
            $obj->editByStep = true;
            $obj->editNbSteps = 2;                
            // $title = EmployeeCandidateTranslator::translateAttribute("employee_candidate.single","ar");
            $obj->after_save_edit = [
                'class' => 'SchoolYear',
                'formulaAttribute' => 'orgunit_campaign_id_id',
                'currmod' => 'sis',
                'currstep' => 5,
            ];
        }
    }

    public static $DB_STRUCTURE = [
        'id' => [
            'SHOW' => false,
            'RETRIEVE' => true,
            'EDIT' => false,
            'TYPE' => 'PK',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],


        'customer_upload_id' => [
            'SHORTNAME' => 'upload',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => true,
            'UTF8' => false,
            'SIZE' => 40,
            'TYPE' => 'FK',
            'ANSWER' => 'customer_upload',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 0,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
        ],

        'orgunit_id' => [
            'SHORTNAME' => 'orgunit',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 40,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'orgunit',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 0,
            'QSEARCH' => '',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_50',
            'READONLY' => true,
        ],

        'levels_template_id' => [
            'IMPORTANT' => 'IN',
            'TYPE' => 'FK',
            'ANSWER' => 'levels_template',
            'CATEGORY' => 'SHORTCUT',
            'SHORTCUT' => 'orgunit_id.levels_template_id',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'ANSMODULE' => 'sis',
            'DISPLAY' => '',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
        ],

        'campaign_id' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 32,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'INT',
            // 'ANSWER' => 'FUNCTION',
            // 'ANSMODULE' => 'sis',
            'DISPLAY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
            'READONLY' => true,
        ],

        'orgunit_campaign_id_id' => [
            'IMPORTANT' => 'IN',
            'TYPE' => 'FK',
            'ANSWER' => 'orgunit_campaign_id',
            'CATEGORY' => 'FORMULA',
            'SIZE' => 40,
            'DEFAUT' => 0,
            'ANSMODULE' => 'sis',
            'DISPLAY' => '',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'READONLY' => true,
            'CSS' => 'width_pct_25',
            'RELATION' => 'OneToMany', 
        ],

        'candidate_hdate' => [
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 10,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'DATE',
            'FORMAT' => 'HIJRI_UNIT',
            'READONLY' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],


        'customer_id' => [
            'SHORTNAME' => 'customer',
            'SEARCH' => false,
            'SHOW' => false,
            'RETRIEVE' => false,
            'EDIT' => false,
            'READONLY' => true,
            'UTF8' => false,
            'SIZE' => 40,
            'TYPE' => 'FK',
            'ANSWER' => 'customer',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 0,
            'AUTOCOMPLETE' => true,
            'RELATION' => 'OneToMany', 
            'REQUIRED' => true,
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'PLACE-HOLDER' => 'write here the IDN of the customer',
            'CSS' => 'width_pct_50',
        ],

        'customer_created' => [
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'READONLY' => true,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 1,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],

        'full_name' => array('IMPORTANT' => 'IN',  'SEARCH' => true,  'SHOW' => true,  'RETRIEVE' => true,  'EDIT' => true, 
                'READONLY' => true,  'SIZE' => 128, 'MAXLENGTH' => 128, 'UTF8' => true,  
				'TYPE' => 'TEXT',  'MINIBOX' => true,    'DISPLAY' => true,  'STEP' => 1, 'QSEARCH' => true, 
				'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 'MANDATORY' => true, 
				'CSS' => 'width_pct_100',),

        'birth_date_en' => array(
					'TYPE' => 'GDAT',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'SEARCH' => true, 
					'FORMAT' => '',  'MINIBOX' => true,  
					'MANDATORY' => false,    'DISPLAY' => true, 'STEP' => 1,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true, 
					'CSS' => 'width_pct_25',),                


        'start_date_en' => array(
                        'TYPE' => 'GDAT',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'SEARCH' => true, 
                        'FORMAT' => '',  'MINIBOX' => true,  
                        'MANDATORY' => false,    'DISPLAY' => true, 'STEP' => 1,  
                        'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true, 
                        'CSS' => 'width_pct_25',),                
    

        'age' => array('STEP' => 2,  
					'TYPE' => 'INT',  'EDIT' => true,  
					'CATEGORY' => 'FORMULA',  'SHOW' => true,  'RETRIEVE' => true, 
					'UNIT' => 'سنة', "NO-HZM-UNIT" => true, 'READONLY' => true,  
					'CONSTRAINTS' => ['f-between;2,65'],  
					'MANDATORY' => false,    'DISPLAY' => true,  
					'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '',  'ERROR-CHECK' => true,  
					'CSS' => 'width_pct_25',),                    

        'presence' => array('STEP' => 1,  
						'CATEGORY' => '',  'EDIT' => true,  'QEDIT' => false,  'SHOW' => true,  'RETRIEVE' => false, 
						'SEARCH' => true,  'QSEARCH' => false,  'SEARCH-MANDATORY' => true,  'SEARCH-DEFAULT' => true, 
						'QSEARCH' => true,  'DEFAUT' => 1,  'SHOW-ADMIN' => true,  'ROLES' => 6,  
						'MINIBOX' => true,  'DISPLAY' => true,  
						'DISPLAY-UGROUPS' => '',  'EDIT-UGROUPS' => '', 
						'CSS' => 'width_pct_25',
						'MANDATORY' => true,  'UTF8' => false,  
						'TYPE' => 'ENUM',  'ANSWER' => "FUNCTION",  
						'RELATION' => 'ManyToOne',  'READONLY' => false, ),

		     

        'jobrole_mfk' => ['STEP' => 2, 
                        'IMPORTANT' => 'IN',
                        'SEARCH' => true,
                        'EDIT' => true,
                        'TYPE' => 'MFK',
                        'ANSWER' => 'jobrole',
                        'ANSMODULE' => 'ums',
                        'SIZE' => 32,
                        'QSEARCH' => true,
                        'RETRIEVE' => true,
                        'DISPLAY' => '',
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'UTF8' => true,
                        'CSS' => 'width_pct_25',
                    ],                        

        
        'comments' => [
            'STEP' => 2,
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 255,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => true,
            'TYPE' => 'TEXT',
            'DISPLAY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],
                        

        'candidate_status_id' => [
            'STEP' => 2,
            'IMPORTANT' => 'IN',
            'SEARCH' => true,
            'SHOW' => true,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 40,
            'SEARCH-ADMIN' => true,
            'SHOW-ADMIN' => true,
            'EDIT-ADMIN' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'candidate_status',
            'ANSMODULE' => 'sis',
            'DEFAUT' => 1,
            'READONLY' => true,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_25',
        ],
        

        

        'created_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'created_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'updated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_by' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'auser',
            'ANSMODULE' => 'ums',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'validated_at' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'TYPE' => 'GDAT',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'active' => [
            'SHOW-ADMIN' => true,
            'RETRIEVE' => false,
            'EDIT' => false,
            'QEDIT' => false,
            'DEFAUT' => 'Y',
            'TYPE' => 'YN',
            'DISPLAY' => '',
            'STEP' => 99,
            'DISPLAY-UGROUPS' => '',
            'EDIT-UGROUPS' => '',
            'CSS' => 'width_pct_100',
        ],

        'version'                  => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),
		
		'update_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		
		'delete_groups_mfk'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		
		'display_groups_mfk'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 
				'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		
		'sci_id'                        => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 
				'TYPE' => 'INT', /*stepnum-not-the-object*/ 'FGROUP' => 'tech_fields'),
		
		'tech_notes' 	                => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA',
                "SHOW-ADMIN" => true, 'EDIT' => false, 'QEDIT' => false,
				'TOKEN_SEP'=>"§", 'READONLY'=>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),
    ];
}
?>
